/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Tools.FonctionMetier;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Scanner;


/**
 *
 * @author Jacob
 */
public class FrmAjouterMedocs extends javax.swing.JFrame {

    /**
     * Creates new form FrmAjouterMedocsJacob
     */
    public FonctionMetier fm;
    public FrmAjouterMedocs() {
       
        initComponents();
        fm = new FonctionMetier();
        List<String> famLibArr = fm.getFamLib();
        for(String fam : famLibArr) 
        {
             cboFamille.addItem(fam);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomMedoc = new javax.swing.JTextField();
        cboFamille = new javax.swing.JComboBox<>();
        txtCompo = new javax.swing.JTextField();
        txtEffets = new javax.swing.JTextField();
        txtContreIndication = new javax.swing.JTextField();
        txtPrixEchantillon = new javax.swing.JTextField();
        lblNomMedoc = new javax.swing.JLabel();
        lblFamille = new javax.swing.JLabel();
        lblCompo = new javax.swing.JLabel();
        lblEffets = new javax.swing.JLabel();
        lblContreIndication = new javax.swing.JLabel();
        lblPrixEchantillon = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboFamille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFamilleActionPerformed(evt);
            }
        });

        lblNomMedoc.setText("Nom du médicament :");

        lblFamille.setText("famille :");

        lblCompo.setText("Composition :");

        lblEffets.setText("Effets : ");

        lblContreIndication.setText("Contre-indication :");

        lblPrixEchantillon.setText("Prix d'un échantillon :");

        btnInsert.setBackground(new java.awt.Color(0, 102, 102));
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setText("Insérer");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTittle.setText("Ajouter médicaments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrixEchantillon, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(lblContreIndication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCompo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomMedoc)
                    .addComponent(lblEffets, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFamille, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEffets, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContreIndication, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCompo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboFamille, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtPrixEchantillon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnInsert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomMedoc))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamille)
                    .addComponent(cboFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEffets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEffets))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContreIndication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContreIndication))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrixEchantillon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrixEchantillon))
                .addGap(32, 32, 32)
                .addComponent(btnInsert)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void cboFamilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFamilleActionPerformed

    }//GEN-LAST:event_cboFamilleActionPerformed

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
       if(txtNomMedoc.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Saisir un Nom","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
       }
       else if(txtCompo.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Saisir une composition","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
       
       }
       else if(txtEffets.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Saisir un effet","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
       
       }
       else if(txtContreIndication.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Saisir une contre-indication","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
       
       }
       else if(txtPrixEchantillon.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Saisir un prix d'échantillon","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
       
       }
       /*else if(txtPrixEchantillon.getText().)
       {
       JOptionPane.showMessageDialog(this,"Saisir un nombre","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
       }*/
       else
       {
            Boolean success = fm.addMedoc(txtNomMedoc.getText(), String.valueOf(cboFamille.getSelectedItem()), txtCompo.getText(), txtEffets.getText(), txtContreIndication.getText(), Float.parseFloat(txtPrixEchantillon.getText()));
            if(success)
                JOptionPane.showMessageDialog(this,"Le médicament a bien été enregistré","Information",JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,"Problème interne","Information",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_btnInsertMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAjouterMedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAjouterMedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAjouterMedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAjouterMedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAjouterMedocs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JComboBox<String> cboFamille;
    private javax.swing.JLabel lblCompo;
    private javax.swing.JLabel lblContreIndication;
    private javax.swing.JLabel lblEffets;
    private javax.swing.JLabel lblFamille;
    private javax.swing.JLabel lblNomMedoc;
    private javax.swing.JLabel lblPrixEchantillon;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTextField txtCompo;
    private javax.swing.JTextField txtContreIndication;
    private javax.swing.JTextField txtEffets;
    private javax.swing.JTextField txtNomMedoc;
    private javax.swing.JTextField txtPrixEchantillon;
    // End of variables declaration//GEN-END:variables
}
