/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Vue.FrmListerIndividus;
import Vue.FrmListerIndividus;
import Vue.FrmAJouterPrescription;
import Vue.FrmAJouterPrescription;
import Vue.FrmStat;
import Vue.FrmAjouterMedocs;
import Vue.FrmAjouterMedocs;
import Vue.FrmListerIndividus;
import Vue.FrmModifierIndividus;
import Vue.FrmStat;

/**
 *
 * @author athid
 */
public class FrmAcceuil extends javax.swing.JFrame 
{

    /**
     * Creates new form FrmAcceuil
     */
    public FrmAcceuil() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrescription = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnModifierMedoc = new javax.swing.JButton();
        btnListerMedoc = new javax.swing.JButton();
        btnAjouterMedoc2 = new javax.swing.JButton();
        btnAjouterIndividu = new javax.swing.JButton();
        btnModifierIndividu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnListerIndividu = new javax.swing.JButton();
        btnStat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnInteraction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPrescription.setBackground(new java.awt.Color(0, 102, 102));
        btnPrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescription.setText("Prescrire");
        btnPrescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrescriptionMouseClicked(evt);
            }
        });
        btnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Médicament");

        btnModifierMedoc.setBackground(new java.awt.Color(0, 102, 102));
        btnModifierMedoc.setForeground(new java.awt.Color(255, 255, 255));
        btnModifierMedoc.setText("Modifier");
        btnModifierMedoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMedocMouseClicked(evt);
            }
        });
        btnModifierMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierMedocActionPerformed(evt);
            }
        });

        btnListerMedoc.setBackground(new java.awt.Color(0, 102, 102));
        btnListerMedoc.setForeground(new java.awt.Color(255, 255, 255));
        btnListerMedoc.setText("Lister");
        btnListerMedoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListerMedocMouseClicked(evt);
            }
        });
        btnListerMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListerMedocActionPerformed(evt);
            }
        });

        btnAjouterMedoc2.setBackground(new java.awt.Color(0, 102, 102));
        btnAjouterMedoc2.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouterMedoc2.setText("Ajouter");
        btnAjouterMedoc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMedoc2MouseClicked(evt);
            }
        });
        btnAjouterMedoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterMedoc2ActionPerformed(evt);
            }
        });

        btnAjouterIndividu.setBackground(new java.awt.Color(0, 102, 102));
        btnAjouterIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouterIndividu.setText("Ajouter");
        btnAjouterIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterIndividuMouseClicked(evt);
            }
        });
        btnAjouterIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterIndividuActionPerformed(evt);
            }
        });

        btnModifierIndividu.setBackground(new java.awt.Color(0, 102, 102));
        btnModifierIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnModifierIndividu.setText("Modifier");
        btnModifierIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierIndividuMouseClicked(evt);
            }
        });
        btnModifierIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierIndividuActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Individu");

        btnListerIndividu.setBackground(new java.awt.Color(0, 102, 102));
        btnListerIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnListerIndividu.setText("Lister");
        btnListerIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListerIndividuMouseClicked(evt);
            }
        });
        btnListerIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListerIndividuActionPerformed(evt);
            }
        });

        btnStat.setBackground(new java.awt.Color(0, 102, 102));
        btnStat.setForeground(new java.awt.Color(255, 255, 255));
        btnStat.setText("Statistiques");
        btnStat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatMouseClicked(evt);
            }
        });
        btnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setText("GSB");

        btnInteraction.setBackground(new java.awt.Color(0, 102, 102));
        btnInteraction.setForeground(new java.awt.Color(255, 255, 255));
        btnInteraction.setText("Interaction");
        btnInteraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInteractionMouseClicked(evt);
            }
        });
        btnInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnModifierIndividu, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(btnAjouterIndividu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListerIndividu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjouterMedoc2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifierMedoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListerMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInteraction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStat, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addComponent(btnListerIndividu)
                        .addGap(16, 16, 16)
                        .addComponent(btnAjouterIndividu)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifierIndividu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListerMedoc)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouterMedoc2)
                            .addComponent(btnPrescription))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModifierMedoc)
                            .addComponent(btnStat))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInteraction)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatActionPerformed

    private void btnStatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatMouseClicked
        // TODO add your handling code here:
        FrmStat Statistique = new FrmStat();
        Statistique.setVisible(true);
    }//GEN-LAST:event_btnStatMouseClicked

    private void btnListerIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListerIndividuActionPerformed
        // TODO add your handling code here:
        FrmListerIndividus Lister = new FrmListerIndividus();
        Lister.setVisible(true);
    }//GEN-LAST:event_btnListerIndividuActionPerformed

    private void btnListerIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListerIndividuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListerIndividuMouseClicked

    private void btnModifierIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierIndividuActionPerformed
        // TODO add your handling code here:
        FrmModifierIndividus ModifierTI = new FrmModifierIndividus();
        ModifierTI.setVisible(true);
    }//GEN-LAST:event_btnModifierIndividuActionPerformed

    private void btnModifierIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierIndividuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierIndividuMouseClicked

    private void btnAjouterIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterIndividuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterIndividuActionPerformed

    private void btnAjouterIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterIndividuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterIndividuMouseClicked

    private void btnAjouterMedoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterMedoc2ActionPerformed
        // TODO add your handling code here:
        FrmAjouterMedocs AjouterM = new FrmAjouterMedocs();
        AjouterM.setVisible(true);
    }//GEN-LAST:event_btnAjouterMedoc2ActionPerformed

    private void btnAjouterMedoc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMedoc2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterMedoc2MouseClicked

    private void btnListerMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListerMedocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListerMedocActionPerformed

    private void btnListerMedocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListerMedocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListerMedocMouseClicked

    private void btnModifierMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierMedocActionPerformed
        // TODO add your handling code here:
        FrmModifierMedocs modifierMedocs = new FrmModifierMedocs();
        modifierMedocs.setVisible(true);
    }//GEN-LAST:event_btnModifierMedocActionPerformed

    private void btnModifierMedocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMedocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierMedocMouseClicked

    private void btnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionActionPerformed
        // TODO add your handling code here:
        FrmAJouterPrescription Prescription = new FrmAJouterPrescription();
        Prescription.setVisible(true);
    }//GEN-LAST:event_btnPrescriptionActionPerformed

    private void btnPrescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrescriptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrescriptionMouseClicked

    private void btnInteractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInteractionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInteractionMouseClicked

    private void btnInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteractionActionPerformed
        // TODO add your handling code here:
        FrmMedicamentNonConseillé Interaction = new FrmMedicamentNonConseillé();
        Interaction.setVisible(true);
    }//GEN-LAST:event_btnInteractionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAcceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterIndividu;
    private javax.swing.JButton btnAjouterMedoc2;
    private javax.swing.JButton btnInteraction;
    private javax.swing.JButton btnListerIndividu;
    private javax.swing.JButton btnListerMedoc;
    private javax.swing.JButton btnModifierIndividu;
    private javax.swing.JButton btnModifierMedoc;
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
